import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/header";

export const metadata: Metadata = {
  title: "Clone inspire of Brainhub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="relative bg-gray-200 w-full h-[130.25rem] text-left text-[0.88rem] text-white font-inter">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
